name: Deploy to VPS

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            cd /srv/gardening/backend/production
            git pull origin main
            sudo systemctl restart gardening-backend-prod
          else
            cd /srv/gardening/backend/test
            git pull origin develop
            sudo systemctl restart gardening-backend-test
          fi

