name: Deploy to VPS

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            cd /srv/gardening/backend/production
            git pull origin main
            sudo /bin/pkill -f "/srv/gardening/backend/production"
            go mod tidy
            sudo /bin/systemctl restart gardening-backend-prod.service
          else
            cd /srv/gardening/backend/test
            git pull origin develop
            sudo /bin/pkill -f "/srv/gardening/backend/production"
            go mod tidy
            sudo /bin/systemctl restart gardening-backend-test.service
          fi

